version: '2'
services:

    zabbix-db-storage:
      image: busybox:latest
      volumes:
        - /var/lib/mysql

    zabbix-db:
      image: zabbix/zabbix-db-mariadb
      volumes:
        - /backups:/backups
        - /etc/localtime:/etc/localtime:ro
      volumes_from:
        - zabbix-db-storage
      environment:
        - MARIADB_USER=zabbix
        - MARIADB_PASS=my_password

    zabbix-server:
      image: zabbix/zabbix-3.0:latest
      ports:
        - "80:80"
        - "10051:10051"
      volumes:
        - /etc/localtime:/etc/localtime:ro
      links:
        - zabbix-db:zabbix.db
      environment:
        - ZS_DBHost=zabbix.db
        - ZS_DBUser=zabbix
        - ZS_DBPassword=my_password

    dynamo:
        build:
          ./docker/dynamo

    dynamo0:
        build:
          ./docker/dynamo
        ports:
            - "8080:8080"

    haproxy:
        build: ./docker/haproxy

    consul-main:
        image: progrium/consul:latest
        hostname: "consul-main"
        ports:
          - "8400:8400"
          - "8500:8500"
          - "53:53"
        command: "-server -data-dir /tmp/consul -bootstrap"

    consulserver:
        image: gliderlabs/consul-server:latest
        container_name: consulserver
        ports:
           - "8300"
           - "8400"
           - "8500:8500"
           - "53"
        command: -data-dir /tmp/consul -bootstrap -client 0.0.0.0

    # Example of a service.. Access ip addresses at http://localhost:8500/v1/catalog/service/web-test
    web-test:
        image: yeasy/simple-web:latest
        environment:
          SERVICE_80_NAME: web-test
          SERVICE_NAME: web-test
          SERVICE_TAGS: web-test 
        ports:
        - "80"

    registrator:
        image: gliderlabs/registrator:master
        container_name: registrator
        network_mode: host
        links:
          - "consulserver:consul"
        volumes:
           - "/var/run/docker.sock:/tmp/docker.sock"
        command: -internal consul://consul:8500

    consultemplate:
        image: yeasy/nginx-consul-template:latest
        container_name: consultemplate
        hostname: consultemplate
        links:
          - "consulserver:consul"
        ports:
          - "80:80"
